#pragma once

#include "glm.hpp"

// WINDOW
#define WINDOW_DEFAULT_SIZE glm::vec2(1920, 1080)
#define WINDOW_TITLE "The Survival Game"

// RENDER
#define RENDER_MULTISAMPLING_SAMPLE_COUNT 4
#define RENDER_VERTEX_STRIDE 6               // CHANGE THIS NUMBER WHEN U CHANGE VERTEX ATTRIB POINTERS PLS DONT FORGET LOLOLO
#define RENDER_CAMERA_NEAR 0.1f
#define RENDER_CAMERA_FAR 1000.0f

// PHYSICS
#define PHYSICS_MAX_STEP_COUNT 10
#define PHYSICS_RATE 120

// LIGHTING
#define LIGHTING_SUN_DIRECTION glm::vec3(-0.5f, -1.0f, -0.3f)
#define LIGHTING_SUN_INTENSITY 1.0f
#define LIGHTING_SUN_COLOR glm::vec4(1.0f, 1.0f, 1.0f, 1.0f)
#define LIGHTING_SHADOW_RANGE 50.0f
#define LIGHTING_SHADOW_RES glm::vec2(256, 256)
#define LIGHTING_MAX_POINT_LIGHTS 32
#define LIGHTING_MAX_POINT_LIGHT_FALLBACK_RANGE 100.0f
#define LIGHTING_AMBIENT_STRENGTH 0.2f

// TERRAIN
#define TERRAIN_GRID_SIZE 1.0f
#define TERRAIN_GRID_COUNT 500
#define TERRAIN_HEIGHT_SCALE 7.5f
#define TERRAIN_NOISE_FREQUENCY 0.0175f
#define TERRAIN_MOUNTAIN_NOISE_FREQUENCY 0.00125f
#define TERRAIN_MOUNTAIN_HEIGHT_SCALE 50.0f

// MAP
#define MAP_TREE_GRID_SIZE 15.0f
#define MAP_TREE_SPAWN_MIN_VAL 0.43f
#define MAP_TREE_FREQUENCY 0.01f

// CHARACTER
#define CHARACTER_SPEED 10.0f
#define CHARACTER_CAMERA_LERP_SPEED 100.0f
#define CHARACTER_CAMERA_SPEED 12.5f
#define CHARACTER_MOUSE_SENSITIVITY 100.0f
#define CHARACTER_DEBUG_FLY_SPEED 100.0f
#define CHARACTER_MAX_TOOL_REACH 3.5f
#define CHARACTER_GRAB_DISTANCE 3.5f
